### PR TITLE
added checks for header files

### PR DESCRIPTION
**Pull request by aniketmdinde**
Added checks for header files.

### CODE REVIEW

**Comment by heinsaar** [comment]
@aniketmdinde Thanks, although your changes trigger [a build fail](https://github.com/heinsaar/kaizen/actions/runs/6349290077/job/17247780107?pr=23). Looks like you've forgotten to `import fnmatch` at the top of `make_kaizen.py`.

This should have showed up in your local runs too. You can run locally as [described here](https://github.com/heinsaar/kaizen#build--run-on-windows--linux-including-wsl).

Also, whenever there's an issue for a change, just copy the issue title when describing the commit message and prefix the issue number with 'Fix' if it's a closing change, like so: 
> Check that all headers have #pragma once Fix #11

The 'Fix' prefix is just for automation. It's okay if you forget it occasionally - we all do - we'll then close manually once build & tests pass.

In general, we follow a standardized practice for all commit messages described [here](https://www.heinsaar.com/p/rapid-practice.html). The relevant parts in this case are this:

image

And this:

image
        
And so on. More in the link

**Comment by aniketmdinde** [comment]
let me make the changes plz

**Comment by aniketmdinde** [comment]
there was a typo in pragma_once check wjich i also resolved now....

**Comment by heinsaar** [comment]
> there was a typo in pragma_once check wjich i also resolved now....

Ah, right, thanks.

**Comment by aniketmdinde** [comment]
All the checks have successfully completed. Thank you for giving me this opportunity and your guidance.  Looking forward to contribute more asap.

**Comment by heinsaar** [comment]
@aniketmdinde Excellent, thanks for your contribution as well, I've already merged it.

I just noticed that your checks are at the end of the script. It makes more sense to do them closer to the top, before any further processing. Could you please move them right after:
```python
zen_datas      = os.path.join(project_dir, 'zen/datas')
zen_functions  = os.path.join(project_dir, 'zen/functions')
zen_composites = os.path.join(project_dir, 'zen/composites')
```
For the commit message, you can use this: **Move `#pragma once` checks closer to beginning**

**Comment by aniketmdinde** [comment]
sure

**Pull request merged**
